version: '3.2'

services:
#  service:
#    container_name: personal-finances-service
#    build: .
#    ports:
#      - 3000:3000
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@database:5432/finances
#    depends_on:
#      - database

  database:
    container_name: personal-finances-database
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: personal-finances-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    logging:
      driver: none

volumes:
  postgres_data:
