version: '3.2'

services:
  database:
    container_name: personal-finances-database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: personal-finances-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    logging:
      driver: none

volumes:
  postgres_data:
