version: "3.1"

services:
  database:
    image: mongo
    container_name: personal-finances-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: finances
      MONGO_INITDB_ROOT_PASSWORD: finances
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb_data:
    driver: local
