version: "3.3"

services:
  service:
    build: .
    container_name: personal-finances-service
    restart: always
    env_file:
      - ./env/service/.env  
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: personal-finances-database
    env_file:
      - ./env/mongodb/.env
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

networks:
  default:
    external:
      name: personal-finances-network
